# Generated by Django 2.2.2 on 2019-06-22 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postfeed',
            options={'ordering': ['user', 'slug']},
        ),
    ]
