# Generated by Django 2.2.2 on 2019-06-26 00:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190624_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postfeed',
            options={'ordering': ['-published_date', 'user', 'slug']},
        ),
        migrations.AddField(
            model_name='postfeed',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
