# Generated by Django 3.0.3 on 2020-03-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_auto_20200226_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='slug',
            field=models.SlugField(default='nKRTpm30'),
        ),
    ]
