# Generated by Django 3.0.3 on 2020-03-06 11:42

import connections.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_auto_20200306_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='slug',
            field=models.SlugField(default=connections.models.generate_id),
        ),
    ]
