# Generated by Django 2.2.2 on 2019-06-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(default='user<built-in function id>', max_length=255, unique=True)),
                ('email_id', models.EmailField(default='<django.db.models.fields.CharField>@mysite.com', max_length=254, unique=True)),
                ('mobile_number', models.IntegerField(null=True, unique=True)),
                ('date_of_birth', models.DateField()),
                ('bio', models.TextField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
