# Generated by Django 2.2.5 on 2019-10-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20190928_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='friend',
            field=models.BooleanField(default=False),
        ),
    ]
