# Generated by Django 2.2.5 on 2019-10-19 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_connections_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connections',
            name='friend',
        ),
    ]
