# Generated by Django 3.0.3 on 2020-02-26 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20200225_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='slug',
            field=models.SlugField(default='9q_UHOtG'),
        ),
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='R1ohXK_B')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_request', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
