# Generated by Django 3.0.3 on 2020-02-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20200226_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='connection',
            name='slug',
            field=models.SlugField(default='cUZNTORx'),
        ),
        migrations.DeleteModel(
            name='ConnectionRequest',
        ),
    ]
