# Generated by Django 3.0.3 on 2020-02-26 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20200226_0652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
