# Generated by Django 2.2.5 on 2019-10-01 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-commented_time']},
        ),
        migrations.CreateModel(
            name='ReplyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('reply_time', models.DateTimeField(auto_now_add=True)),
                ('replY_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply_by', to=settings.AUTH_USER_MODEL)),
                ('reply_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_on_comment', to='comments.Comments')),
            ],
            options={
                'ordering': ['-reply_time'],
            },
        ),
    ]
