# Generated by Django 2.2.5 on 2019-10-01 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190928_1312'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_auto_20191001_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('commented_time', models.DateTimeField(auto_now_add=True)),
                ('comment_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_on', to='posts.PostFeed')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-commented_time'],
            },
        ),
        migrations.RenameField(
            model_name='replycomment',
            old_name='replY_sender',
            new_name='reply_sender',
        ),
        migrations.RenameField(
            model_name='replycomment',
            old_name='reply',
            new_name='reply_text',
        ),
        migrations.AlterField(
            model_name='replycomment',
            name='reply_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_on_comment', to='comments.Comment'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
