# Generated by Django 2.2.5 on 2019-10-01 21:12

import comments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20191002_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default=comments.models.generate_id, max_length=35, unique=True),
        ),
    ]
