# Generated by Django 2.2.5 on 2019-10-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20191017_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default='awr2FBfxOK', max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='replycomment',
            name='slug',
            field=models.SlugField(default='k4lpmwNHGY1e', max_length=12, unique=True),
        ),
    ]
