# Generated by Django 2.2.5 on 2019-10-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20191017_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default='p81x6y3vrO', max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='replycomment',
            name='slug',
            field=models.SlugField(default='PJGWfCb3rTBp', max_length=12, unique=True),
        ),
    ]
