# Generated by Django 2.2.5 on 2019-10-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_auto_20191019_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default='GjMyCk7bqd', max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='replycomment',
            name='slug',
            field=models.SlugField(default='pF29yMAUd9vw', max_length=12, unique=True),
        ),
    ]
