# Generated by Django 3.0.1 on 2020-01-09 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_auto_20191019_0556'),
        ('likes', '0002_auto_20200109_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replycommentlikes',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_reply_comment', to='comments.ReplyComment'),
        ),
    ]
