# Generated by Django 3.0.2 on 2020-01-14 03:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_auto_20190928_1312'),
        ('comments', '0010_auto_20191019_0556'),
        ('likes', '0003_auto_20200109_1925'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentLikes',
            new_name='CommentLike',
        ),
        migrations.RenameModel(
            old_name='PostLikes',
            new_name='PostLike',
        ),
        migrations.RenameModel(
            old_name='ReplyCommentLikes',
            new_name='ReplyCommentLike',
        ),
    ]
