# Generated by Django 3.0.3 on 2020-02-26 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0004_auto_20200114_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlike',
            old_name='post',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='replycommentlike',
            old_name='post',
            new_name='reply',
        ),
    ]
